# Welcome to Jekyll!

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Garrett Lam"
title_separator          : #"-"
name                     : ""
description              : "Welcome to my portfolio"
url                      : https://garrett-lam.github.io
baseurl                  : "/" 
repository               : "garrett-lam/https://garrett-lam.github.io"
remote_theme             : "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin    : "default" # "default", "dark", "contrast", "dirt"

# Site Author
author:
  # Biographic information
  avatar           : "/docs/images/profile.png"
  name             : "Garrett Lam"
  pronouns         : #
  bio              : ""
  location         : "Boston, MA"
  employer         : "Harvard Medical School & Massachusetts General Hospital"
  uri              : # URL
  email            : "garrettlam9@gmail.com"

   # Academic websites
  arxiv            : # URL - Update with the correct link to your profile
  googlescholar    : #
  impactstory      : # URL
  orcid            : #
  semantic         : # URL
  pubmed           : #
  researchgate     : # URL
  scopus           : # URL

  # Repositories and software development
  bitbucket        : # Username - Update with your username on the site
  codepen          : # Username
  dribbble         : # Username
  github           : "garrett-lam"
  kaggle           : # Username  
  stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")    

  # Social media
  bluesky          : #
  facebook         : # Username
  flickr           : # Username
  foursquare       : # Username
  goodreads        : # Username
  google_plus      : # Username
  keybase          : # Username
  instagram        : # Username
  lastfm           : # Username
  linkedin         : "https://linkedin.com/in/garrett-lam"
  mastodon         : # URL
  medium           : # URL
  pinterest        : # Username
  soundcloud       : # Username
  steam            : # Username
  telegram         : # URL
  tumblr           : # Username
  twitter          : # Username for X / Twitter
  vine             : # Username
  weibo            : # Username
  wikipedia        : # Username
  xing             : # Username
  youtube          : # Username
  zhihu            : # Username

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Tell Minimal Mistakes to include custom CSS

defaults:
  - scope:
      path: ""
      type: ""
    values:
      custom_css: assets/css/custom.css

# defaults:
#   - scope:
#       path: "_pages"
#       type: "pages"
#     values:
#       layout: single
#       author_profile: true
#       custom_css: assets/css/custom.css

#   - scope:
#       path: "_pages"
#       type: "posts"
#     values:
#       custom_css: assets/css/custom.css

#   - scope:
#       path: "_pages"
#       type: "portfolio"
#     values:
#       custom_css: assets/css/custom.css

# Plugins
plugins:
  - jekyll-include-cache
